version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "3000:80"
